"""drop redundant unique constraints on subscriptions

Revision ID: 066f0a8a71f7
Revises: 0002_audio_assets
Create Date: 2026-08-31 12:10:30.595589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066f0a8a71f7'
down_revision: Union[str, None] = '0002_audio_assets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subscriptions_paystack_subscription_code_key'), 'subscriptions', type_='unique')
    op.drop_constraint(op.f('subscriptions_reference_key'), 'subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('subscriptions_reference_key'), 'subscriptions', ['reference'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('subscriptions_paystack_subscription_code_key'), 'subscriptions', ['paystack_subscription_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
