"""added image url to db gift preference

Revision ID: 3957bc6acd4f
Revises: edbb9f3c5654
Create Date: 2026-09-22 05:03:49.824532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3957bc6acd4f'
down_revision: Union[str, None] = 'edbb9f3c5654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
