"""intergrate frontend

Revision ID: 4d0cd1a2924a
Revises: 20260908_redeem_vouchers
Create Date: 2026-09-22 04:21:15.931402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d0cd1a2924a'
down_revision: Union[str, None] = '20260908_redeem_vouchers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redeem_codes_code_hash'), table_name='redeem_codes')
    op.create_index(op.f('ix_redeem_codes_code_hash'), 'redeem_codes', ['code_hash'], unique=False)
    op.create_unique_constraint(None, 'redeem_codes', ['code_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redeem_codes', type_='unique')
    op.drop_index(op.f('ix_redeem_codes_code_hash'), table_name='redeem_codes')
    op.create_index(op.f('ix_redeem_codes_code_hash'), 'redeem_codes', ['code_hash'], unique=True)
    # ### end Alembic commands ###
