"""chat bot

Revision ID: 71a63fc4c209
Revises: 42f6f046783e
Create Date: 2026-10-03 01:05:52.804754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a63fc4c209'
down_revision: Union[str, None] = '42f6f046783e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_help_articles_fts'), table_name='help_articles', postgresql_using='gin', postgresql_where='(is_published = true)')
    op.drop_constraint(op.f('help_conversations_public_id_key'), 'help_conversations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('help_conversations_public_id_key'), 'help_conversations', ['public_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_help_articles_fts'), 'help_articles', [sa.literal_column('(((setweight(to_tsvector(\'english\'::regconfig, COALESCE(title, \'\'::character varying)::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(search_keywords, \'\'::text)), \'A\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(excerpt, \'\'::text)), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(content, \'\'::text)), \'C\'::"char"))')], unique=False, postgresql_using='gin', postgresql_where='(is_published = true)')
    # ### end Alembic commands ###
