"""cleanup git catalog

Revision ID: 93cd3f207615
Revises: 184c1929a911
Create Date: 2026-09-01 20:23:27.504751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cd3f207615'
down_revision: Union[str, None] = '184c1929a911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gift_catalog_sync_last_successful_sync_at'), 'gift_catalog_sync', ['last_successful_sync_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_catalog_sync_last_successful_sync_at'), table_name='gift_catalog_sync')
    # ### end Alembic commands ###
