"""cleanup legacy event preferences

Revision ID: adab87076c3b
Revises: 0003_event_alert_preferences
Create Date: 2026-09-01 18:27:20.290088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adab87076c3b'
down_revision: Union[str, None] = '0003_event_alert_preferences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_preferences_gift_custom_audio_id'), 'user_preferences', type_='foreignkey')
    op.drop_column('user_preferences', 'event_speech_enabled')
    op.drop_column('user_preferences', 'gift_system_sound_id')
    op.drop_column('user_preferences', 'gift_alert_enabled')
    op.drop_column('user_preferences', 'gift_tts_provider')
    op.drop_column('user_preferences', 'gift_tts_template')
    op.drop_column('user_preferences', 'event_speech_template')
    op.drop_column('user_preferences', 'gift_volume')
    op.drop_column('user_preferences', 'gift_tts_voice')
    op.drop_column('user_preferences', 'gift_fish_model')
    op.drop_column('user_preferences', 'gift_fish_voice_id')
    op.drop_column('user_preferences', 'gift_alert_type')
    op.drop_column('user_preferences', 'gift_custom_audio_url')
    op.drop_column('user_preferences', 'gift_speed')
    op.drop_column('user_preferences', 'gift_custom_audio_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('gift_custom_audio_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_speed', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('gift_custom_audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_alert_type', sa.VARCHAR(), server_default=sa.text("'tts'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('gift_fish_voice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_fish_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_tts_voice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_volume', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('event_speech_template', sa.VARCHAR(), server_default=sa.text("'{{user}} sent {{gift}}'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('gift_tts_template', sa.VARCHAR(), server_default=sa.text("'{{user}} sent {{gift}}'::character varying"), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('gift_tts_provider', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('gift_alert_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_preferences', sa.Column('gift_system_sound_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_preferences', sa.Column('event_speech_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_user_preferences_gift_custom_audio_id'), 'user_preferences', 'audio_assets', ['gift_custom_audio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
