"""fix mig errors

Revision ID: e0a539bfa11b
Revises: 20260904_payment_history_method
Create Date: 2026-09-04 16:13:59.455348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a539bfa11b'
down_revision: Union[str, None] = '20260904_payment_history_method'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'muted_users', ['owner_id', 'tiktok_username'])
    op.drop_index(op.f('ix_payment_history_provider_reference'), table_name='payment_history')
    op.drop_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', type_='unique')
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.create_unique_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_payment_history_provider_reference'), 'payment_history', ['provider_reference'], unique=False)
    op.drop_constraint(None, 'muted_users', type_='unique')
    # ### end Alembic commands ###
