"""added image url to db gift preference

Revision ID: edbb9f3c5654
Revises: 4d0cd1a2924a
Create Date: 2026-09-22 05:03:33.559645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edbb9f3c5654'
down_revision: Union[str, None] = '4d0cd1a2924a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_preferences', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_preferences', 'image_url')
    # ### end Alembic commands ###
