"""fix articles

Revision ID: f5a445515f5b
Revises: 7acd48a1aa40
Create Date: 2026-10-02 22:38:22.086259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a445515f5b'
down_revision: Union[str, None] = '7acd48a1aa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help_articles', sa.Column('search_keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('help_articles', 'search_keywords')
    # ### end Alembic commands ###
