"""subscription migrations

Revision ID: f94a1a9959f4
Revises: 20260906_subscription_upgrades
Create Date: 2026-09-06 11:39:23.824779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94a1a9959f4'
down_revision: Union[str, None] = '20260906_subscription_upgrades'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_upgrades_new_subscription_code'), table_name='subscription_upgrades')
    op.drop_index(op.f('ix_subscription_upgrades_payment_reference'), table_name='subscription_upgrades')
    op.drop_index(op.f('ix_subscription_upgrades_status'), table_name='subscription_upgrades')
    op.drop_index(op.f('ix_subscription_upgrades_subscription_id'), table_name='subscription_upgrades')
    op.drop_index(op.f('ix_subscription_upgrades_user_id'), table_name='subscription_upgrades')
    op.drop_table('subscription_upgrades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_upgrades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payment_reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('old_plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_interval', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_subscription_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_authorization_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('old_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('old_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('new_plan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_interval', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('new_subscription_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_authorization_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('remaining_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('old_plan_price_kobo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_plan_price_kobo', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unused_value_kobo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('upgrade_amount_kobo', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('credit_duration_seconds', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('first_debit', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('payment_amount_kobo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_channel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending_payment'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('subscription_upgrades_subscription_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscription_upgrades_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_upgrades_pkey')),
    sa.UniqueConstraint('payment_reference', name=op.f('subscription_upgrades_payment_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('reference', name=op.f('subscription_upgrades_reference_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_subscription_upgrades_user_id'), 'subscription_upgrades', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscription_upgrades_subscription_id'), 'subscription_upgrades', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_upgrades_status'), 'subscription_upgrades', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_upgrades_payment_reference'), 'subscription_upgrades', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_subscription_upgrades_new_subscription_code'), 'subscription_upgrades', ['new_subscription_code'], unique=False)
    # ### end Alembic commands ###
